### ISSUE TITLE
reconstructions uses cluster objects on publicdb.

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#179]
Today the reconstructions of events of station 14001 crashed on pique:

```
2017-11-06 13:24:19,267 - INFO - [3733] - Updating event histograms for Summary: 14001 - 05 Nov 2017
2017-11-06 13:24:20,428 - ERROR - [3733] - Exception occured.
Traceback (most recent call last):
  File "scripts/hisparc-update.py", line 44, in <module>
    run()
  File "scripts/hisparc-update.py", line 27, in run
    completed = update_all_histograms()
  File "scripts/../publicdb/histograms/jobs.py", line 187, in update_all_histograms
    perform_update_tasks()
  File "scripts/../publicdb/histograms/jobs.py", line 210, in perform_update_tasks
    update_histograms()
  File "scripts/../publicdb/histograms/jobs.py", line 328, in update_histograms
    perform_events_tasks)
  File "scripts/../publicdb/histograms/jobs.py", line 379, in perform_tasks_manager
    summary, tmp_locations = perform_certain_tasks(summary)
  File "scripts/../publicdb/histograms/jobs.py", line 401, in perform_events_tasks
    esd.reconstruct_events_and_store_temporary_esd(summary))
  File "scripts/../publicdb/histograms/esd.py", line 183, in reconstruct_events_and_store_temporary_esd
    reconstruct.reconstruct_and_store()
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/sapphire/analysis/reconstructions.py", line 134, in reconstruct_and_store
    self.reconstruct_directions(detector_ids=detector_ids)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/sapphire/analysis/reconstructions.py", line 151, in reconstruct_directions
    initials)
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/sapphire/analysis/direction_reconstruction.py", line 116, in reconstruct_events
    for event, initial in events_init]
  File "/srv/publicdb/publicdb_env/lib/python2.7/site-packages/sapphire/analysis/direction_reconstruction.py", line 77, in reconstruct_event
    self.station.cluster.set_timestamp(event['timestamp'])
AttributeError: 'NoneType' object has no attribute 'cluster'
```

I turned off `MULTIPROCESSING` and added `verbose=True` to `esd.py` [here](https://github.com/HiSPARC/publicdb/blob/master/publicdb/histograms/esd.py#L180)

This results in the output (along with the error):

```
Read object None from datafile.
```
[This is from a try except thing here](https://github.com/HiSPARC/sapphire/blob/master/sapphire/analysis/reconstructions.py#L107)

Apparently the `cluster` objects are being read from the ESD file instead of constructed using `sapphire.HiSPARCStations`. Today station 14001 was missing from the cluster in het ESD file, and it all crashed.

Proposed solution: Remove this part from `ReconstructESDEvents` and create a separate `ReconstructSimulatedEvents` that tries to read the `cluster` object.

**Comment by tomkooij** [comment]
Fixed in HiSPARC/sapphire@fe522682cc0747ba9d31e67ea967c863fe0399ff
