### ISSUE TITLE
Some bugs in master

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#79]
There are some bugs in SAPPHiRE causing exceptions (reported by @davidfokkema )

```python
from sapphire.clusters import ScienceParkCluster
cluster = ScienceParkCluster()
```
gives

    Traceback (most recent call last):
     File "<ipython-input-3-079abf44332d>", line 1, in <module>
       cluster = ScienceParkCluster()
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/clusters.py", line 766, in __init__
       self._add_station(enu, alpha, detectors, station)
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/clusters.py", line 432, in _add_station
       detector_timestamps, number))
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/clusters.py", line 204, in __init__
       if len(station_timestamps) == len(self.x):
    TypeError: object of type 'int' has no len()

and
```python
from sapphire import esd
from sapphire.analysis import reconstructions
data = esd.quick_download(501)
rec = reconstructions.ReconstructESDEvents(data, data.root.s501, 501)
rec.reconstruct_and_store()
```

Gives:

    Traceback (most recent call last):
     File "<ipython-input-8-e4ce8b56f245>", line 1, in <module>
       rec.reconstruct_and_store()
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/analysis/reconstructions.py", line 88, in reconstruct_and_store
       self.station)
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/analysis/calibration.py", line 52, in determine_detector_timing_offsets
       offsets[id] = determine_detector_timing_offset(dt, dz)
     File "/Users/david/work/HiSPARC/software/sapphire/sapphire/analysis/calibration.py", line 79, in determine_detector_timing_offset
       if abs(detector_offset) > 100:
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by 153957** [comment]
First part fixed in dae2287d637f28207222c2fadd72d1c521a88a1f
